# Generated by Django 4.0.1 on 2022-01-06 13:27

import app_hospital.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=25, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=25, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=25, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('telephone_number', models.IntegerField(blank=True, verbose_name='Telephone number')),
                ('location', models.ImageField(blank=True, null=True, upload_to=app_hospital.models.upload_location_path, verbose_name='Location')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hospital.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25, verbose_name='Full name')),
                ('full_name_en', models.CharField(max_length=25, null=True, verbose_name='Full name')),
                ('full_name_fa', models.CharField(max_length=25, null=True, verbose_name='Full name')),
                ('email', models.IntegerField(blank=True, null=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_hospital.models.upload_image_path, verbose_name='Image')),
                ('is_morning_shift', models.BooleanField(default=True, verbose_name='Morning shift')),
                ('is_night_shift', models.BooleanField(default=True, verbose_name='Night shift')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hospital.hospital', verbose_name='Hospital')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hospital.specialty', verbose_name='Specialty')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hospital.province', verbose_name='Province'),
        ),
    ]
